name: Deploy DotNet project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'                # Set your Azure Function App name here
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'                    # Adjust if project is in a specific folder
  DOTNET_VERSION: '6.0.x'                                # Specify the .NET version

jobs:
  build-and-deploy:
    runs-on: windows-latest                              # Change to ubuntu-latest if using Linux

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v4

    - name: 'List Directory Contents'                    # Step to verify the structure
      run: |
        echo "Listing root directory contents"
        ls -R
        echo "Checking for CarApp/CarApp.csproj specifically"
        ls CarApp || echo "CarApp directory not found"

    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Restore Dependencies'
      run: dotnet restore './CarApp/CarApp.csproj'       # Adjust path if needed based on ls output

    - name: 'Build Project'
      run: dotnet build './CarApp/CarApp.csproj' --configuration Debug

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './CarApp/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
