name: Deploy DotNet project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'                # Set to your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'                    # Set to root or the folder containing CarApp
  DOTNET_VERSION: '6.0.x'                                # Set .NET version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest                              # Change to ubuntu-latest for Linux
    environment: dev                                     # Update based on environment

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v4

    - name: 'List Directory Contents'                    # Debugging step
      run: ls -R                                         # Lists contents to confirm file paths

    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Restore Project Dependencies'
      shell: pwsh                                        # Use bash if on Linux
      run: dotnet restore './CarApp/CarApp.csproj'       # Ensure path is correct

    - name: 'Build Project'
      shell: pwsh
      run: dotnet build './CarApp/CarApp.csproj' --configuration Release --output ./output

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
