name: Deploy DotNet project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'                    # Your Azure Function App name
  DOTNET_VERSION: '6.0.x'                                    # .NET version

jobs:
  build-and-deploy:
    runs-on: windows-latest                                  # Use ubuntu-latest if deploying on Linux

    steps:
    # Step 1: Checkout code from the repository
    - name: 'Checkout Code'
      uses: actions/checkout@v4

    # Step 2: Confirm working directory
    - name: 'Show Working Directory'
      run: |
        echo "Current working directory:"
        pwd

    # Step 3: List all files and directories to locate CarApp.csproj
    - name: 'List Directory Contents'
      run: |
        echo "Listing all files in the repository to locate CarApp.csproj:"
        ls -R

    # Step 4: Dynamically set the path for CarApp.csproj based on directory structure
    - name: 'Locate CarApp.csproj'
      id: locate-project
      run: |
        if [[ -f "./CarApp/CarApp.csproj" ]]; then
          echo "Project file found at CarApp/CarApp.csproj"
          echo "PROJECT_PATH=CarApp/CarApp.csproj" >> $GITHUB_ENV
        elif [[ -f "./CarApp.csproj" ]]; then
          echo "Project file found at CarApp.csproj"
          echo "PROJECT_PATH=CarApp.csproj" >> $GITHUB_ENV
        else
          echo "Error: Project file not found in expected locations."
          exit 1
        fi

    # Step 5: Setup the .NET environment based on the specified version
    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Step 6: Restore dependencies using the located project path
    - name: 'Restore Project Dependencies'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    # Step 7: Build the project using the specified configuration
    - name: 'Build Project'
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Debug

    # Step 8: Deploy to Azure Function App
    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './output'                                  # Adjust if output directory differs
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
