name: Deploy to Server

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'  # Use the appropriate .NET version for your project

      - name: Build project
        run: dotnet build CarApp.sln --configuration Release

      - name: Publish project
        run: dotnet publish CarApp.sln --configuration Release --output ./out

      - name: Deploy to Server
        run: |
          echo "Deploying to server..."
          # Customize this part with your actual deployment commands
          # You might use SCP, FTP, or another method for deployment
          # Example using SCP:
          # scp -r ./out/* user@your-server:/path/to/deploy
