# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List directory contents
      run: |
        echo "Listing directory contents:"
        ls -R

    - name: Check for CarApp.csproj
      run: |
        echo "Checking for CarApp.csproj in the repository:"
        if [ -f "./CarApp/CarApp.csproj" ]; then
          echo "CarApp.csproj found."
        else
          echo "CarApp.csproj not found in ./CarApp/!"
          exit 1
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CarApp/CarApp.csproj

    - name: Build
      run: dotnet build CarApp/CarApp.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test CarApp/CarApp.csproj --no-build --verbosity normal
