name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: CarApp.sln                        
      Project_Path: CarApp/CarApp.csproj                

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install .NET SDK
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}

    # Build the project
    - name: Build the project
      run: dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }}

    # Execute unit tests
    - name: Execute unit tests
      run: dotnet test ${{ env.Project_Path }} --configuration ${{ matrix.configuration }}

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: ${{ env.Project_Path }}/bin/${{ matrix.configuration }}
